#!/usr/bin/python
import main, sys

try:
    wiki_article = sys.argv[1]
    question_text = sys.argv[2]
except:
    print 'ERROR: args error'
    sys.exit(1)

try:
    main.main()
except:
    print 'ERROR: nlp data reading error'
    sys.exit(1)

try:
    docs = main.read_sentences_from_file(wiki_article)
    docs_q = main.read_sentences_from_file(question_text, False, True)
except:
    print 'ERROR: docs reading error'
    sys.exit(1)

try:
    main.answering(docs, docs_q)
except:
    print 'ERROR: answering error'
    sys.exit(1)
