#!/usr/bin/python
import main, sys

wiki_article = sys.argv[1]
question_text = sys.argv[2]

main.main()

docs = main.read_sentences_from_file(wiki_article)
docs_q = main.read_sentences_from_file(question_text, False, True)

main.answering(docs, docs_q)
